package ru.vtb24.it.ivr.ivrtypes.v1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2017-08-20T16:03:14.266+03:00
 * Generated source version: 2.7.3
 * 
 */
@WebServiceClient(name = "GetCreditClientInfoPortService", 
                  wsdlLocation = "file:/C:/PROJECTS/My_Test/My_TestChild_2/src/main/resources/GetCreditClientInfo.wsdl",
                  targetNamespace = "http://www.vtb24.ru/IT/IVR/IVRTypes/v1.0") 
public class GetCreditClientInfoPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.vtb24.ru/IT/IVR/IVRTypes/v1.0", "GetCreditClientInfoPortService");
    public final static QName GetCreditClientInfoPortSoap11 = new QName("http://www.vtb24.ru/IT/IVR/IVRTypes/v1.0", "GetCreditClientInfoPortSoap11");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/PROJECTS/My_Test/My_TestChild_2/src/main/resources/GetCreditClientInfo.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(GetCreditClientInfoPortService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/PROJECTS/My_Test/My_TestChild_2/src/main/resources/GetCreditClientInfo.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public GetCreditClientInfoPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public GetCreditClientInfoPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public GetCreditClientInfoPortService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GetCreditClientInfoPortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GetCreditClientInfoPortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public GetCreditClientInfoPortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns GetCreditClientInfoPort
     */
    @WebEndpoint(name = "GetCreditClientInfoPortSoap11")
    public GetCreditClientInfoPort getGetCreditClientInfoPortSoap11() {
        return super.getPort(GetCreditClientInfoPortSoap11, GetCreditClientInfoPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GetCreditClientInfoPort
     */
    @WebEndpoint(name = "GetCreditClientInfoPortSoap11")
    public GetCreditClientInfoPort getGetCreditClientInfoPortSoap11(WebServiceFeature... features) {
        return super.getPort(GetCreditClientInfoPortSoap11, GetCreditClientInfoPort.class, features);
    }

}
