package com.sap.document.sap.soap.functions.mc_style;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2017-09-29T14:06:41.403+03:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZSI_BP_AIRPIN")
@XmlSeeAlso({ObjectFactory.class})
public interface ZSIBPAIRPIN {

    @WebMethod(operationName = "ZfmShanAirpinSoapServHead")
    @RequestWrapper(localName = "ZfmShanAirpinSoapServHead", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZfmShanAirpinSoapServHead")
    @ResponseWrapper(localName = "ZfmShanAirpinSoapServHeadResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.sap.document.sap.soap.functions.mc_style.ZfmShanAirpinSoapServHeadResponse")
    public void zfmShanAirpinSoapServHead(
        @WebParam(name = "IvCardNum", targetNamespace = "")
        java.lang.String ivCardNum,
        @WebParam(name = "IvTelNum", targetNamespace = "")
        java.lang.String ivTelNum,
        @WebParam(mode = WebParam.Mode.OUT, name = "EvGuidCadr", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> evGuidCadr,
        @WebParam(mode = WebParam.Mode.OUT, name = "EvRezult", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> evRezult
    );
}
